### ISSUE TITLE
[Bug]: Boats are unbreakable.

### ISSUE THREAD

**Issue by jabthetab** [samedifferent/Ecologics#110]
### Mod Version

2.1.12

### Mod Loader

Fabric

### Mod Loader Version

0.14.14

### What happened?

I hope this shows the bug well enough. Featuring some genuine confusion as this was clipped when I was just playing on my own.
https://user-images.githubusercontent.com/95195478/219689054-3d21b5c4-a746-470e-9774-ca18695c303c.mp4

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/10767926/latest.log)

**Comment by PhoenixVX** [comment]
Please upload the whole log file. Right now, I can only guess that a mod which allows you to modify entity velocity is currently breaking the boats, but I can't tell because the log includes the absolute bare minimum necessary to debug this issue. I recommend https://mclo.gs to upload your logs as it censors any information that could be considered identifiable.

**Comment by jabthetab** [comment]
> Please upload the whole log file. Right now, I can only guess that a mod which allows you to modify entity velocity is currently breaking the boats, but I can't tell because the log includes the absolute bare minimum necessary to debug this issue. I recommend https://mclo.gs to upload your logs as it censors any information that could be considered identifiable.

I'm so sorry, it said to upload latest.log. I sorta thought it was a bit short but didn't really question it because it was 2AM heh.
I hope [this log](https://mclo.gs/nMgG0yA) has enough data to work with. Sorry again.
