### ISSUE TITLE
[Bug]: Error while starting server with Universal Bone Meal mod enabled

### ISSUE THREAD

**Issue by Preciel** [samedifferent/Ecologics#22]
### Mod Version

1.5.1

### Mod Loader

Forge

### Mod Loader Version

40.0.36

### What happened?

If both mods Ecologics and Universal Bone Meal are enabled, the following error will be dumbed while starting the minecraft server.

### latest.log

[latest.log](https://github.com/samedifferent/Ecologics/files/8418998/latest.log)
[debug.log](https://github.com/samedifferent/Ecologics/files/8418999/debug.log)

**Comment by samedifferent** [comment]
Please post the _full_ latest.log file.

**Comment by Fuzss** [comment]
Original report on my repo: https://github.com/Fuzss/universalbonemeal-forge/issues/1

**Comment by samedifferent** [comment]
The issue is not on Ecologic's part, as it only occurs when UBM is installed. I also created a dummy mod that just has a loot modifier via the datapack, and the issue occurred. Refer to the [universal bonemeal issue thread](https://github.com/Fuzss/universalbonemeal-forge/issues/1) for further updates.
