### ISSUE TITLE
[Bug]: Not really a bug but Thin ice doesn't create water blocks after being broken

### ISSUE THREAD

**Issue by babacon88** [samedifferent/Ecologics#78]
### Mod Version

1.19

### Mod Loader

Forge

### Mod Loader Version

forge 1.19

### What happened?

Unlike vanilla ice pack, thin ice does not goes back to water block after being broken, causing uneven/broken water surfaces

### latest.log

Its not really a bug but I hope you guys fix it next update

**Comment by samedifferent** [comment]
This is intentional because it's supposed to be a trap. If it turned into water, the player would just be able to swim out. it would literally serve no purpose. If you have any ideas for how we can change the thin ice concept, then feel free to suggest it.

**Comment by babacon88** [comment]
> This is intentional because it's supposed to be a trap. If it turned into water, the player would just be able to swim out. it would literally serve no purpose. If you have any ideas for how we can change the thin ice concept, then feel free to suggest it.

Can you make them spawn water like their vanilla counterpart? Beside this is an in an effective trap for you can break vanilla ice next to them or head to open water to get back up. Not melting back into water would make them inconsistent and illogical as an ice block. many of times missing water blocks cant be refill normally by surrounding water and difficult to refill manually. Frost Walkers will also find this tedious, which i suggest having thin ice turned into regular ice upon being walked on by Frost walker enchantment, or spawn water block, wihch will instantly turnback into ice, or both, which is best.

**Comment by Jusey1** [comment]
> 

It's an ineffective trap either way since there isn't much that would kill the player in this instance. Thin ice should create water blocks after being broken but then make it so that in frozen biomes, the player sinks much faster and the water will freeze back to ice after the player has fallen. That way, thin ice will become water, player will quickly sink as the water freezes above them, and thus it becomes an effective trap... Otherwise, thin ice is a mild annoyance at best and should just be disabled as it doesn't offer any thrilling challenge or danger as is.
